### ISSUE TITLE
Modulino Distance incorrect ID

### ISSUE THREAD

**Issue by mo-seph** [arduino/arduino-modulino-mpy#3]
The ModulinoDistance library reports an incorrect ID for the modulino board:
```
>>> from modulino import ModulinoDistance
>>> d = ModulinoDistance()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/modulino/distance.py", line 10, in __init__
  File "/lib/modulino/lib/vl53l4cd.py", line 92, in __init__
RuntimeError: Wrong sensor ID (236) or type!
```

I've also tried using the address written on the board (0x52) but then I get an IO error when it tries to write:
```
>>> d = ModulinoDistance(address=0x52)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/modulino/distance.py", line 10, in __init__
  File "/lib/modulino/lib/vl53l4cd.py", line 90, in __init__
  File "/lib/modulino/lib/vl53l4cd.py", line 206, in model_info
  File "/lib/modulino/lib/vl53l4cd.py", line 452, in _read_register
OSError: [Errno 5] EIO
```

The only config I've changed is editing __init__.py to remove the import of pressure.py, as it's not currently referenced by package.json.

**Comment by mo-seph** [comment]
Edit to add - i've got a ModulinoKnob and ModulinoPixels, and they are both working.

**Comment by sebromero** [comment]
Thank you @mo-seph for reporting this issue. That's odd. It reports a different model of the distance sensor. Can you try [this](https://github.com/arduino-libraries/Modulino/blob/main/examples/Modulino_Distance/Basic/Basic.ino) Arduino sketch and tell me if it works?

**Comment by mo-seph** [comment]
> Thank you @mo-seph for reporting this issue. That's odd. It reports a different model of the distance sensor. Can you try [this](https://github.com/arduino-libraries/Modulino/blob/main/examples/Modulino_Distance/Basic/Basic.ino) Arduino sketch and tell me if it works?

Yes - that works fine, numbers appear, they look to be roughly correct in mm

**Comment by sebromero** [comment]
@mo-seph Okay, that's interesting. It gives me a starting point for debugging. I'll follow up shortly.

**Comment by sebromero** [comment]
Okay, so it seems that the Arduino sketch only works by accident due to a bug in the underlying library. I submitted a fix for it [here](https://github.com/stm32duino/VL53L4CD/pull/11). While this doesn't solve your problem, it means that the MicroPython library would probably work as well with whatever version of this sensor you have if we ignore the sensor ID.
If you just want to get it working, for now you can likely just comment out [those two lines](https://github.com/arduino/arduino-modulino-mpy/blob/main/src/modulino/lib/vl53l4cd.py#L91-L92).

**Comment by mo-seph** [comment]
That works, thanks!
